### PR TITLE
rely on udev to manage symlinks, closes #2

### LINKED ISSUE #2: Symlinks are not updated after a reboot
Hi Oogali,

Thanks for researching and documenting this C5/M5 instance family nvme issue we are all plagued with!

While implementing your solution, I noticed that the current script does not handle incorrect symlinks. By this I mean that on an instance with multiple EBS volumes already attached and a new volume is added  it is possible that when this instance is rebooted it comes back with different mapping than on previous runs of the script, this is especially the case with multiple EBS volumes attached.

For what it's worth, in our limited observations the smaller EBS volumes appear to have higher precedence than larger EBS volumes.

To remedy this I have written a new bash script which is heavily inspired by your research and wanted to submit it to you. The script is available on my gist and if you feel it worthwhile I am happy to submit a PR.

https://gist.github.com/brahman81/04d1d19b81f78385aacf0a9a3a3afe26

Kind Regards,

### PR DESCRIPTION
**Pull request by brahman81**
* uses `xvd` notation to match Ubuntu default for Xen virtual devices
 * uses [:space:] character set to delete all whitespace
 * move script to `/usr/local/sbin` as this is a system script

### CODE REVIEW

File: ebs-nvme-mapping.sh [hunk 1]
```diff
@@ -1,10 +1,21 @@
 #!/bin/bash
```
Comment (zymergen-vdc) [inline ebs-nvme-mapping.sh:1]: The name of this file doesn't match the udev rule reference.

Comment (brahman81) [reply ebs-nvme-mapping.sh:1]: Good catch! Just submitted a fix.

**Comment by Kasama** [comment]
It would probably be nice to update the README as well to make sure the explanation match the actual provided files.

**Comment by b-dean** [comment]
Using this PR I still get the wrong devices for the root device:
```
[root@ip-10-75-0-84 ec2-user]# ls -l /dev/xv*
lrwxrwxrwx 1 root root 7 Mar  9 20:07 /dev/xvda -> nvme1n1
lrwxrwxrwx 1 root root 9 Mar  9 20:07 /dev/xvda1 -> nvme0n1p1
lrwxrwxrwx 1 root root 7 Mar  9 20:07 /dev/xvdb -> nvme2n1
```
when it should be `/dev/nvme0n1p2`
```
[root@ip-10-75-0-84 ec2-user]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/nvme0n1p2   10G  3.2G  6.9G  32% /
devtmpfs        3.7G     0  3.7G   0% /dev
tmpfs           3.7G     0  3.7G   0% /dev/shm
tmpfs           3.7G   17M  3.7G   1% /run
tmpfs           3.7G     0  3.7G   0% /sys/fs/cgroup
tmpfs           753M     0  753M   0% /run/user/1000
```
(note that I don't have the xvdb mounted anywhere, was just adding another block device)

The vendor specific info says sda1 for the device that ends up on `/`. This is a RHEL-7 AMI.

Should there be a `/dev/xvda2`?

File: ebs-nvme-mapping.sh [hunk 2]
```diff
@@ -1,10 +1,21 @@
...
+# Inspired by https://github.com/oogali/ebs-automatic-nvme-mapping
```
Comment (oogali) [inline ebs-nvme-mapping.sh:2]: I assume this comment block was from your gist, I don't think this needs to be incorporated upstream.

File: ebs-nvme-mapping.sh [hunk 3]
```diff
@@ -1,10 +1,21 @@
...
 
-PATH="${PATH}:/usr/sbin"
-
-for blkdev in $( nvme list | awk '/^\/dev/ { print $1 }' ) ; do
-  mapping=$(nvme id-ctrl --raw-binary "${blkdev}" | cut -c3073-3104 | tr -s ' ' | sed 's/ $//g')
-  if [[ "${mapping}" == /dev/* ]]; then
-    ( test -b "${blkdev}" && test -L "${mapping}" ) || ln -s "${blkdev}" "${mapping}"
-  fi
-done
+if [[ -x /usr/sbin/nvme ]] && [[ -b ${1} ]]; then
```
Comment (oogali) [inline ebs-nvme-mapping.sh:8]: If your test conditions are not matched, this script will silently fail (with a return value of zero).

A better option would be to invert the test conditions, as to be loud and verbose that we can't find the `nvme` program and that a required argument is missing.

File: ebs-nvme-mapping.sh [hunk 4]
```diff
@@ -1,10 +1,21 @@
...
+  # capture 32 bytes at an offset of 3072 bytes from the raw-binary data
+  # not all block devices are extracted with /dev/ prefix
+  # use `xvd` prefix instead of `sd`
+  # remove all trailing space
+  nvme_link=$( \
+    /usr/sbin/nvme id-ctrl --raw-binary "${1}" | \
```
Comment (oogali) [inline ebs-nvme-mapping.sh:14]: If the required argument passed is not a valid path to a block device -- should we complain? Or should we let `nvme` complain and have the user decipher its error message?
